# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en"
  # contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[fr]
  languageCode = "fr"
  contentDir = "content/fr"
  title = "Chinese website title..."
  [fr.params]
    description = "Site description in Chinese..."
  [[fr.menu.main]]
    name = "Wo"
    url = "#about"
    weight = 1
